version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:7.0
    container_name: mcq-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: online-mcq-system
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./scripts/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - mcq-network

  # Backend API
  backend:
    build: .
    container_name: mcq-backend
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PORT: 5000
      MONGODB_URI: mongodb://admin:password123@mongodb:27017/online-mcq-system?authSource=admin
      JWT_SECRET: your-super-secret-jwt-key-change-this-in-production-environment-2024
      JWT_EXPIRES_IN: 7d
      FRONTEND_URL: http://localhost:5173
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    networks:
      - mcq-network
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  mongodb_data:

networks:
  mcq-network:
    driver: bridge
